---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: locations-manager
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - cluster.karmada.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - locations.miloapis.com
  resources:
  - locationclasses
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - locations.miloapis.com
  resources:
  - locationclasses/finalizers
  verbs:
  - update
- apiGroups:
  - locations.miloapis.com
  resources:
  - locations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - locations.miloapis.com
  resources:
  - servinglocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.karmada.io
  resources:
  - clusterpropagationpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
