namespace: locations-system

images:
  - name: ghcr.io/milo-os/locations
    newTag: dev

resources:
  - ../../base/crd
  - ../../base/manager

components:
  - ../../components/namespace
  - ../../components/controller_rbac

configMapGenerator:
  - name: locations-config
    behavior: replace
    files:
      - config.yaml
    options:
      disableNameSuffixHash: true

patches:
  - path: dev_patch.yaml
