//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&LocationOperator{}, func(obj interface{}) { SetObjectDefaults_LocationOperator(obj.(*LocationOperator)) })
	return nil
}

func SetObjectDefaults_LocationOperator(in *LocationOperator) {
	SetDefaults_LocationOperator(in)
	SetDefaults_MetricsServerConfig(&in.MetricsServer)
	SetDefaults_TLSConfig(&in.MetricsServer.TLS)
	SetDefaults_LocationPublisherConfig(&in.LocationPublisher)
	SetDefaults_ClientConnectionConfig(&in.LocationPublisher.Client)
	if in.LocationPublisher.Client.QPS == 0 {
		in.LocationPublisher.Client.QPS = 50
	}
	if in.LocationPublisher.Client.Burst == 0 {
		in.LocationPublisher.Client.Burst = 100
	}
}
