//go:build !ignore_autogenerated

// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package config

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientConnectionConfig) DeepCopyInto(out *ClientConnectionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientConnectionConfig.
func (in *ClientConnectionConfig) DeepCopy() *ClientConnectionConfig {
	if in == nil {
		return nil
	}
	out := new(ClientConnectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocationOperator) DeepCopyInto(out *LocationOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.MetricsServer.DeepCopyInto(&out.MetricsServer)
	in.LocationPublisher.DeepCopyInto(&out.LocationPublisher)
	out.LocationReadiness = in.LocationReadiness
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocationOperator.
func (in *LocationOperator) DeepCopy() *LocationOperator {
	if in == nil {
		return nil
	}
	out := new(LocationOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LocationOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocationPublisherConfig) DeepCopyInto(out *LocationPublisherConfig) {
	*out = *in
	out.SafetyResyncPeriod = in.SafetyResyncPeriod
	if in.LocationScopedResources != nil {
		in, out := &in.LocationScopedResources, &out.LocationScopedResources
		*out = make([]LocationScopedResource, len(*in))
		copy(*out, *in)
	}
	out.Client = in.Client
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocationPublisherConfig.
func (in *LocationPublisherConfig) DeepCopy() *LocationPublisherConfig {
	if in == nil {
		return nil
	}
	out := new(LocationPublisherConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocationReadinessConfig) DeepCopyInto(out *LocationReadinessConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocationReadinessConfig.
func (in *LocationReadinessConfig) DeepCopy() *LocationReadinessConfig {
	if in == nil {
		return nil
	}
	out := new(LocationReadinessConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocationScopedResource) DeepCopyInto(out *LocationScopedResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocationScopedResource.
func (in *LocationScopedResource) DeepCopy() *LocationScopedResource {
	if in == nil {
		return nil
	}
	out := new(LocationScopedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsServerConfig) DeepCopyInto(out *MetricsServerConfig) {
	*out = *in
	if in.SecureServing != nil {
		in, out := &in.SecureServing, &out.SecureServing
		*out = new(bool)
		**out = **in
	}
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsServerConfig.
func (in *MetricsServerConfig) DeepCopy() *MetricsServerConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}
